[package]
name = "tui-textarea"
version = "0.0.0"
edition = "2021"

[features]
default = ["crossterm"]

[dependencies]
crossterm = { version = "0.23", optional = true }
tui = "0.18"

[[example]]
name = "minimal"
required-features = ["crossterm"]
