[package]
name = "tui-textarea"
version = "0.0.0"
edition = "2021"

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm", "tui/crossterm"]
termion = ["dep:termion", "tui/termion"]

[dependencies]
crossterm = { version = "0.23", optional = true }
termion = { version = "1.5", optional = true }
tui = { version = "0.18", default-features = false }

[[example]]
name = "minimal"
required-features = ["crossterm"]

[[example]]
name = "termion"
required-features = ["termion"]

[[example]]
name = "editor"
required-features = ["crossterm"]

[[example]]
name = "multi"
required-features = ["crossterm"]

[[example]]
name = "single_line"
required-features = ["crossterm"]
