[alias]
watch-check = ["watch", "-x", "clippy --features search --examples --tests", "-x", "clippy --features tuirs-crossterm,search --no-default-features --examples --tests"]
watch-test = ["watch", "-x", "test --features=search", "-w", "src", "-w", "tests"]
