[alias]
watch-check = ["watch", "-x", "check --examples --features ratatui-crossterm,search --no-default-features --tests", "-x", "check --examples --features search --tests"]
watch-test = ["watch", "-x", "test --features=search -- --skip=src/lib.rs", "-w", "src"]
