name: CI
on: [push, pull_request]

jobs:
  unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo test -- --skip src/lib.rs
        if: ${{ matrix.os != 'windows-latest' }}
      - run: cargo test -- --skip src\lib.rs
        if: ${{ matrix.os == 'windows-latest' }}
  lint:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt -- --check
      - run: cargo clippy --examples --all-features -- -D warnings
      - run: cargo clippy --no-default-features -- -D warnings
      - run: cargo clippy --no-default-features --features termion -- -D warnings
